name: PR check
on: 
  pull_request:
    types:
          - opened
          - synchronize

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      # - name: unit tests
      #   run: npm run test
      # - name: e2e tests
      #   run: npm run e2e
      - name: tests
        run: npm run test-ci