name: Check commit name
on: [pull_request, push]

jobs:
  check-commit-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5